import chalk from "chalk";
import { runBinaryCapture, runBinaryAndExit } from "../core/runBinary.js";
import fs from "node:fs";
import path from "node:path";

export interface GitHooksStatus {
  hooksPath: string | null;
  commitMsgExists: boolean;
  preCommitExists: boolean;
  containsCommitMsgCommand: boolean;
  containsPreCommitCommand: boolean;
}

interface InstallHooksOptions {
  force?: boolean;
}

const expectedGitHooksPath = ".githooks";
const commitMsgCommand = 'npx --no -- oscd commitlint --edit "$1"';
const preCommitCommand = "npx --no -- oscd lint-staged";

export function getStatus(): GitHooksStatus {
  const result = runBinaryCapture("git", ["config", "--get", "core.hooksPath"]);

  const hooksPath = result.status === 0 ? result.stdout.trim() : null;

  const commitMsgHookPath = path.join(
    process.cwd(),
    expectedGitHooksPath,
    "commit-msg",
  );
  const preCommitHookPath = path.join(
    process.cwd(),
    expectedGitHooksPath,
    "pre-commit",
  );
  const commitMsgExists = fs.existsSync(commitMsgHookPath);
  const preCommitExists = fs.existsSync(preCommitHookPath);

  const commitMsgContent = commitMsgExists
    ? fs.readFileSync(commitMsgHookPath, "utf8")
    : null;
  const preCommitContent = preCommitExists
    ? fs.readFileSync(preCommitHookPath, "utf8")
    : null;

  const containsCommitMsgCommand = commitMsgContent
    ? commitMsgContent.includes(commitMsgCommand)
    : false;
  const containsPreCommitCommand = preCommitContent
    ? preCommitContent.includes(preCommitCommand)
    : false;

  return {
    hooksPath,
    commitMsgExists,
    preCommitExists,
    containsCommitMsgCommand,
    containsPreCommitCommand,
  };
}

export function gitHooksCheckHealth(): boolean {
  const {
    hooksPath,
    commitMsgExists,
    preCommitExists,
    containsCommitMsgCommand,
    containsPreCommitCommand,
  } = getStatus();

  if (!hooksPath) {
    console.warn(chalk.yellow("Git hooksPath is not configured."));
  }

  if (hooksPath && hooksPath !== ".githooks") {
    console.warn(
      chalk.yellow(
        `Git hooksPath is set to "${hooksPath}", expected ".githooks".`,
      ),
    );
  }

  if (!commitMsgExists) {
    console.warn(chalk.yellow("commit-msg hook not found in .githooks/"));
  }

  if (!preCommitExists) {
    console.warn(chalk.yellow("pre-commit hook not found in .githooks/"));
  }

  if (commitMsgExists && !containsCommitMsgCommand) {
    console.warn(
      chalk.yellow(
        `commit-msg hook found at "${hooksPath}" but does not contain expected command.`,
      ),
    );
  }

  if (preCommitExists && !containsPreCommitCommand) {
    console.warn(
      chalk.yellow(
        `pre-commit hook found at "${hooksPath}" but does not contain expected command.`,
      ),
    );
  }

  return (
    hooksPath === expectedGitHooksPath &&
    commitMsgExists &&
    preCommitExists &&
    containsCommitMsgCommand &&
    containsPreCommitCommand
  );
}

export async function gitHooksInstall(opts: InstallHooksOptions = {}) {
  const force = !!opts.force;

  const { hooksPath: currentPath } = getStatus();

  if (currentPath && currentPath !== ".githooks") {
    if (!force) {
      console.error(
        chalk.red(`Git hooksPath is already set to "${currentPath}".`),
      );
      console.error(
        chalk.red('OSCD requires core.hooksPath to be ".githooks".'),
      );
      console.error(
        chalk.red(
          'Move your existing hooks to ".githooks" and re-run with --force if you want to override.',
        ),
      );
      process.exit(1);
    }

    console.warn(
      chalk.yellow(
        `Overriding existing hooksPath "${currentPath}" → "${expectedGitHooksPath}".`,
      ),
    );
  }

  // Set hooksPath (explicitly local)
  runBinaryAndExit("git", [
    "config",
    "--local",
    "core.hooksPath",
    expectedGitHooksPath,
  ]);

  // Create hooks
  const hooksPath = path.join(process.cwd(), expectedGitHooksPath);
  fs.mkdirSync(hooksPath, { recursive: true });

  const commitMsgHookPath = path.join(hooksPath, "commit-msg");
  const preCommitHookPath = path.join(hooksPath, "pre-commit");

  const commitMsgScript = `#!/bin/sh
# generated by @omicronenergy/oscd-tooling
${commitMsgCommand}
`;

  const preCommitScript = `#!/bin/sh
# generated by @omicronenergy/oscd-tooling
${preCommitCommand}
`;

  fs.writeFileSync(commitMsgHookPath, commitMsgScript, { mode: 0o755 });
  fs.writeFileSync(preCommitHookPath, preCommitScript, { mode: 0o755 });

  console.log(chalk.green("Hooks installed successfully."));
}
