import chalk from "chalk";
import { runBinaryCapture, runBinaryAndExit } from "../core/runBinary.js";
import fs from "node:fs";
import path from "node:path";

export interface GitHooksStatus {
  hooksPath: string | null;
  commitMsgExists: boolean;
  containsCommand: boolean;
}

interface InstallHooksOptions {
  force?: boolean;
}

const expectedGitHooksPath = ".githooks";
const commitMsgCommand = "npx --no -- commitlint --edit $1";

export function getStatus(): GitHooksStatus {
  const result = runBinaryCapture("git", ["config", "--get", "core.hooksPath"]);

  const hooksPath = result.status === 0 ? result.stdout.trim() : null;

  const commitMsgHookPath = path.join(
    process.cwd(),
    expectedGitHooksPath,
    "commit-msg",
  );
  const commitMsgExists = fs.existsSync(commitMsgHookPath);

  const commitMsgContent = commitMsgExists
    ? fs.readFileSync(commitMsgHookPath, "utf8")
    : null;

  const containsCommand = commitMsgContent
    ? commitMsgContent.includes(commitMsgCommand)
    : false;

  return {
    hooksPath,
    commitMsgExists,
    containsCommand,
  };
}

export function gitHooksCheckHealth(): boolean {
  const { hooksPath, commitMsgExists, containsCommand } = getStatus();

  if (!hooksPath) {
    console.warn(chalk.yellow("Git hooksPath is not configured."));
  }

  if (hooksPath && hooksPath !== ".githooks") {
    console.warn(
      chalk.yellow(
        `Git hooksPath is set to "${hooksPath}", expected ".githooks".`,
      ),
    );
  }

  if (!commitMsgExists) {
    console.warn(chalk.yellow("commit-msg hook not found in .githooks/"));
  }

  if (commitMsgExists && !containsCommand) {
    console.warn(
      chalk.yellow(
        `commit-msg hook found at "${hooksPath}" but does not contain expected command.`,
      ),
    );
  }

  return (
    hooksPath === expectedGitHooksPath && commitMsgExists && containsCommand
  );
}

export async function gitHooksInstall(opts: InstallHooksOptions = {}) {
  const force = !!opts.force;

  const { hooksPath: currentPath } = getStatus();

  if (currentPath && currentPath !== ".githooks") {
    if (!force) {
      console.error(
        chalk.red(`Git hooksPath is already set to "${currentPath}".`),
      );
      console.error(
        chalk.red('OSCD requires core.hooksPath to be ".githooks".'),
      );
      console.error(
        chalk.red(
          'Move your existing hooks to ".githooks" and re-run with --force if you want to override.',
        ),
      );
      process.exit(1);
    }

    console.warn(
      chalk.yellow(
        `Overriding existing hooksPath "${currentPath}" → "${expectedGitHooksPath}".`,
      ),
    );
  }

  // Set hooksPath (explicitly local)
  runBinaryAndExit("git", [
    "config",
    "--local",
    "core.hooksPath",
    expectedGitHooksPath,
  ]);

  // Create hook
  const hooksPath = path.join(process.cwd(), expectedGitHooksPath);
  fs.mkdirSync(hooksPath, { recursive: true });

  const hookPath = path.join(hooksPath, "commit-msg");

  const script = `#!/bin/sh
# generated by @omicronenergy/oscd-tooling
${commitMsgCommand}
`;

  fs.writeFileSync(hookPath, script, { mode: 0o755 });

  console.log(chalk.green("Hooks installed successfully."));
}
